version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper6
    ports:
      - '2186:2186'
  kafka:
    image: wurstmeister/kafka
    container_name: kafka6
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2186
